version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    environment:
      NPM_VERSION: "6.7.0"
    steps:
      - checkout
      - node/install:
          node-version: "11.15"
      # install dependencies in both apps
      - run: node --version
      - run:
          name: Front-end install
          command: |
            npm run frontend:install
      - run:
          name: Back-end install
          command: |
            npm run backend:install
      - run:
          name: Back-end build
          command: |
            npm run backend:build
      - run:
          name: Front-end build
          command: |
            npm run frontend:build			